version: '3.8'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ADMIN
      POSTGRES_DB: cprk_portal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./server/auth-service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:ADMIN@localhost:5432/cprk_portal
      PYTHONPATH: "/project-root/shared"

volumes:
  postgres_data: